### ISSUE TITLE
clean-aindent-mode does not work in the latest emacs pretest

### ISSUE THREAD

**Issue by tuhdo** [pmarinov/clean-aindent-mode#4]
When I move the arrow key down, the whitespace is not cleaned. I use vanilla Emacs.

**Comment by jimparis** [comment]
@pmarinov, you wrote that "traditionally, auto-indent in emacs is defined only as part of newline-and-indent".  However, since Emacs 24.4 (which was released after your comment), `electric-indent-mode` is now enabled by default, which means that auto-indent occurs even with `newline`. 

Based on that, I think @tuhdo has a good point and that it would be nice if `clean-aindent-mode` wrapped `newline` as well.  I've been testing `clean-aindent-mode` with the advice changed to `newline` and it seems to be working fine.  Thanks for writing this!

**Comment by pmarinov** [comment]
@jimparis I understand. I think your suggestion make sense in light of the changes in Emacs 24.4, and it is backward compatible --  if we wrap as an advice on `newline` for 24.4, it should be just fine for users of previous versions, as if there is no indent nothing will be trimmed.

Now, there is one possible concern, if there was no indentation and you walk away from the line, you will see _"auto trimmed 0 chars"_ on the status line. I don't know if this is a problem. What do you think?

**Comment by jimparis** [comment]
That doesn't sound like a problem to me (and it would be easy enough to just not print it if desired).
